
###
GET http://localhost:3003/api/blogs/ HTTP/1.1 200 0

###
GET http://localhost:3003/api/blogs/{replaceIdHere} HTTP/1.1 200 0

###
PUT http://localhost:3003/api/blogs/6545fcd49bc0adc50f31aa32 HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvc2UiLCJpZCI6IjY1NDUzMTYwNWFlYzA2YzQxODM0OWMxNiIsImlhdCI6MTY5OTA4Mzg4MiwiZXhwIjoxNjk5MDg3NDgyfQ.hzJds5fmTAV7H98im2qlxxTpQN_EWg9p6i-yi3Y_b-g

{ 
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 130
}


###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvc2UiLCJpZCI6IjY1NDI5ZjgxYjQzN2NkYWQ5ZGUxNWI4ZCIsImlhdCI6MTY5ODkwMjU2NSwiZXhwIjoxNjk4OTA2MTY1fQ.jQap715jv-mKycDjqU5OfVojG88icb2-nZbqZ800Jug

{
  "title": "Les folles aventures de Jean last",
  "author": "Another Super Author",
  "url": "url.com",
  "likes": 0
}

### 
DELETE http://localhost:3003/api/blogs/65429e5716d0d6dea1c5a4dc HTTP/1.1 200 0 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvc2UiLCJpZCI6IjY1NDI5ZjgxYjQzN2NkYWQ5ZGUxNWI4ZCIsImlhdCI6MTY5ODkwMjU2NSwiZXhwIjoxNjk4OTA2MTY1fQ.jQap715jv-mKycDjqU5OfVojG88icb2-nZbqZ800Jug
