
###
GET http://localhost:3003/api/blogs/ HTTP/1.1 200 0

###
GET http://localhost:3003/api/blogs/{replaceIdHere} HTTP/1.1 200 0

###
PUT http://localhost:3003/api/blogs/{replaceIdHere} HTTP/1.1 
Content-Type: application/json

{

}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxhIiwiaWQiOiI2NTQyOTljYWNkOGIyNjFjNjNjZDhhYmIiLCJpYXQiOjE2OTg4NjM3MjEsImV4cCI6MTY5ODg2NzMyMX0.FW-AWJKVenG1MoqEDUGH56yUtmI2U_jZpGhws3_k0lk

{
  "title": "Le Monde de Narnia",
  "author": "Another Super Author",
  "url": "url.com",
  "likes": 0
}

### 
DELETE http://localhost:3003/api/blogs/6542992c9228b786cd3d5766 HTTP/1.1 200 0 
